[package]
name = "pic12f508sim"
version = "0.1.0"
edition = "2021"
exclude = ["/obj", "/target"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ihex = "3.0.0"
