
use picsim::cpu::CPU;

// Generated by pic-as.exe
const HEX: &str = "
:10000000010AD70C02003E0C0600010C2100080A70
:10001000010243060C0A0E0A0605100A0604100A1D
:02002000080ACC
:021FFE00EA0FE8
:00000001FF
";

fn main() {
    let mut cpu: CPU = CPU::from_hex(HEX);
    println!("w:{}, pc:{:3}, z:{}, c:{}", cpu.w, cpu.pc, cpu.status_z(), cpu.status_c());
    for _ in 0..10000 {
        cpu.tick();
        println!("pc:{:3} prev: {:?}, next: {:?}", cpu.pc, cpu.last_executed_op, cpu.next_op);
    }
}